### ISSUE TITLE
Interior Design: Make a roadmap

### ISSUE THREAD

**Issue by cmwinters** [cmwinters/santa-crew#3]
This is a tracking issue for everything we need to do for interior design. From the discussion here, we'll plan out concrete milestones & next steps.
#### Living Room
- [ ] Figure out what to do with the bay window area
- [ ] Frame & hang some art
  - [ ] Metropolis poster
  - [ ] Enceladus poster
- [ ] Get an area rug
#### Main hallway
- [ ] figure out a solution for shoes
- [ ] Coat rack & mail sorter
- [ ] Figure out what to put where the mirror was
  - gear wall?
  - magic mirror?
#### Dining room

What the hell do we do with this room? Ideas:
- Workstation & gear storage.
  - we have a lot of recreational shit we need to figure out how to store properly. 
- speakers. I want to set up an old school sound system with vinyl, and this could be the perfect place
- beer fridge
#### Kitchen
- Honestly I think we're good here for now
#### Netflix & chill room
- Get some sweet video game art
  - [ ] Super Metroid 
  - [ ] Halo 2
- [ ] bookshelf for video games and controllers
- [ ] speakers
- [ ] mount TV
#### Patio
- [ ] clean concrete, it's gross
- [ ] get a gas grill
- [ ] more strings of lightbulbs above
- [ ] patio furniture
#### Garage
- [ ] weightlifting platform
- take a second pass at storage
  - we need to store all our camping, scuba and climbing gear effectively

Thoughts or additions? Please weight in @mrsweaters @myzerly @tdhartwick 🙏
